// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ00LnredSKbwVgm7vJ2Sw3WVfC0tAEKc',
    appId: '1:671209975748:web:c89e3a2f401b569540fe91',
    messagingSenderId: '671209975748',
    projectId: 'beautysoft-1fa47',
    authDomain: 'beautysoft-1fa47.firebaseapp.com',
    storageBucket: 'beautysoft-1fa47.appspot.com',
    measurementId: 'G-E8ZT9YBNC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0uLwwlrNhPVHrmGpHxq9Jb-3PRMzmqF4',
    appId: '1:671209975748:android:90c0d7f43756035140fe91',
    messagingSenderId: '671209975748',
    projectId: 'beautysoft-1fa47',
    storageBucket: 'beautysoft-1fa47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjh43Dsou7L02kFhTivJK_xMDIygAIllg',
    appId: '1:671209975748:ios:3e2d402df24f9a3840fe91',
    messagingSenderId: '671209975748',
    projectId: 'beautysoft-1fa47',
    storageBucket: 'beautysoft-1fa47.appspot.com',
    iosBundleId: 'com.example.beautySoft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjh43Dsou7L02kFhTivJK_xMDIygAIllg',
    appId: '1:671209975748:ios:0515b7c17c90161640fe91',
    messagingSenderId: '671209975748',
    projectId: 'beautysoft-1fa47',
    storageBucket: 'beautysoft-1fa47.appspot.com',
    iosBundleId: 'com.example.beautySoft.RunnerTests',
  );
}
